import {
  mobile,
  backend,
  creator,
  web,
  javascript,
  typescript,
  html,
  css,
  reactjs,
  redux,
  tailwind,
  nodejs,
  mongodb,
  git,
  accounts,
  docker,
  carrent,
  jobit,
  tripguide,
  threejs,
  nextjs,
  fastapi,
  python,
  langchain,
  openai,
  netflix,
  todoapp,
  twitter,
  messenger,
  airbnb,
  ecommerce,
  aisaas,
  aicompanion,
  quizzy,
  course,
  notion,
  pdfchatnextjs,
  chatpdfpython,
  multiplechatpdf,
  discordbot,
  dalleimage,
  langchaintesting,
  langchainarticle,
  aivoiceassisted,
  openaiwhisper,
  codeswear,
  inventory,
  portfolio,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "project",
    title: "Project",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const services = [
  {
    title: "Accounting & Finance",
    icon: web,
  },
  {
    title: "Full Stack NextJS Developer",
    icon: mobile,
  },
  {
    title: "Backend FastAPI Developer",
    icon: backend,
  },
  {
    title: "Generative AI Developer",
    icon: creator,
  },
];

const technologies = [
  // {
  //   name: "HTML 5",
  //   icon: html,
  // },
  // {
  //   name: "CSS 3",
  //   icon: css,
  // },
  // {
  //   name: "JavaScript",
  //   icon: javascript,
  // },
  {
    name: "TypeScript",
    icon: typescript,
  },
  // {
  //   name: "React JS",
  //   icon: reactjs,
  // },
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  // {
  //   name: "MongoDB",
  //   icon: mongodb,
  // },
  // {
  //   name: "Three JS",
  //   icon: threejs,
  // },
  // {
  //   name: "git",
  //   icon: git,
  // },
  // {
  //   name: "docker",
  //   icon: docker,
  // },
  {
    name: "nextjs",
    icon: nextjs,
  },
  {
    name: "python",
    icon: python,
  },
  {
    name: "fastapi",
    icon: fastapi,
  },
  {
    name: "langchain",
    icon: langchain,
  },
  {
    name: "openai",
    icon: openai,
  },
];

const experiences = [
  {
    title: "Cashier, Asst. Accountant, Import Asst.",
    company_name: "Brilliant Process & Jubilee Corporation - Karachi, Pakistan",
    icon: accounts,
    iconBg: "#383E56",
    date: "Dec 2008 - March 2013",
    points: [
      "Starting Jobs where I handled manual & computerized accounting, Cash Handling and Other Various Documentations.",
    ],
  },
  {
    title: "Accountant Plus Other Back Office Works",
    company_name: "Kamkool Trading Co & Hot N Spicy Restaurant - Dubai, UAE",
    icon: accounts,
    iconBg: "#E6DEDD",
    date: "Jul 2013 - Dec 2018",
    points: [
      "Manage Accounts, Import/Export Documentation, Procurement and Admin Work by implementing Quickbook Accounting System and MS-Office.",
    ],
  },
  {
    title: "Accounts Executive",
    company_name: "APAG Oil & M&N Impex - Karachi, Pakistan",
    icon: accounts,
    iconBg: "#383E56",
    date: "Jun 2019 - PRESENT",
    points: [
      "Managing Accounts and Tax Related Matters.",
    ],
  },
];

const testimonials = [
  {
    testimonial:
      "I thought it was impossible to make a website as beautiful as our product, but Rick proved me wrong.",
    name: "Sara Lee",
    designation: "CFO",
    company: "Acme Co",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    testimonial:
      "I've never met a web developer who truly cares about their clients' success like Rick does.",
    name: "Chris Brown",
    designation: "COO",
    company: "DEF Corp",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    testimonial:
      "After Rick optimized our website, our traffic increased by 50%. We can't thank them enough!",
    name: "Lisa Wang",
    designation: "CTO",
    company: "456 Enterprises",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
];

const projects = [
  {
    name: "Todo App",
    follow: "REPO OF NEXTJS: ",
    follow_link: "https://github.com/Shahnawaz1990/todonextfastapi-app",
    git: "REPO OF FASTAPI: ",
    source_code_link: "https://github.com/Shahnawaz1990/fastapitodo",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1tSf_XSnSNI6baI0KK7WH7ImrO1ppGv3O/view?usp=sharing",
    image: todoapp,
  },
  {
    name: "Netflix Clone",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=mqUN4N2q4qY",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/netflix-clone",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1uMjnRVCs26vREiEniynd8INqVR1_ay_T/view?usp=sharing",
    image: netflix,
    deploy: "Deployed at: ",
    dep_link: "https://netflix-clone-beta-liart-44.vercel.app/auth",

  },
  {
    name: "Twitter Clone",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=ytkG7RT6SvU",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/twittercollegeproject",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1pQ5aURqyKY8HVqyWajGJWDees8gE7EGY/view?usp=sharing",
    image: twitter,
    deploy: "Deployed at: ",
    dep_link: "https://twittercollegeproject-gdfr.vercel.app",
  },
  {
    name: "Messenger",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=PGPGcKBpAk8",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/messengercollegeproject",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1NCT_o6LkyRFsxTf1LSwrtZdJpug6OEiG/view?usp=sharing",
    image: messenger,
    deploy: "Deployed at: ",
    dep_link: "https://messengercollegeproject.vercel.app",
  },
  {
    name: "AirBnB",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=c_-b_isI4vg",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/educationairrentbnb",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1YKqCBgOyfnRXWsH6ERkzT0U36w9uWPcB/view?usp=sharing",
    image: airbnb,

  },
  {
    name: "E-Commerce",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=5miHyP6lExg",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/ecommercecollegeprojects/tree/main",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1j-lZFJqJfu8e6BSWZDbKj-7RFYuMKdZm/view?usp=sharing",
    image: ecommerce,

  },
  {
    name: "AI Saas",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=ffJ38dBzrlY",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/ai-saas-collegeproject",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1-aTba9cY2MxKT3tSTZ3G86lL-wqurgg3/view?usp=sharing",
    image: aisaas,
  },
  {
    name: "AI Companion",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=PjYWpd7xkaM&t=16200s",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/ai-companion-collegeproject",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1yjTKNoUhiLe1PfXBkLvEq8CE1X-bVj57/view?usp=sharing",
    image: aicompanion,
  },
  {
    name: "AI Quiz",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=vIyU4nInlt0",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/quizzy",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1hnVoFdqtvhvnYypmh-jjizuqPqYGBl2y/view?usp=sharing",
    image: quizzy,
  },
  {
    name: "AI Course",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=EGW2HS2tqAQ",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/course",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/193e1kYw5GDOxFUafJ2bCMP0LUbEePVZ2/view?usp=sharing",
    image: course,
  },
  {
    name: "AI Course",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=EGW2HS2tqAQ",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/course",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/193e1kYw5GDOxFUafJ2bCMP0LUbEePVZ2/view?usp=sharing",
    image: course,
  },
  {
    name: "AI Notes",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=olsdGZcRGSQ",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/notioncollegeproject",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/12K2tQDbQw4E3j64SHf3_rmZkYWdxVjxb/view?usp=sharing",
    image: notion,
  },
  {
    name: "AI Chat PDF NextJS",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=oiCFr19NtPo",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/chatpdfnextjs",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1lTxASBo5rPeIpbQem-iNTVNl_-DJg7Ls/view?usp=sharing",
    image: pdfchatnextjs,
  },
  {
    name: "AI Chat PDF Python",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=wUAUdEw5oxM&list=PLMVV8yyL2GN_n41v1ESBvDHwMbYYhlAh1&index=11",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/chatpdfpython",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1xHi9FVHG2_jNQ6wQuWqovsbNPAD60GL2/view?usp=sharing",
    image: chatpdfpython,
  },
  {
    name: "AI Chat Multiple PDF",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=dXxQ0LR-3Hg",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/chatmultiplepdf",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1NM4o1B9uc8TZbnFqEQwcamg2wOszHxBf/view?usp=sharing",
    image: multiplechatpdf,
  },
  {
    name: "AI Discord Chat Bot",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=BP-w99ZINTc&list=PLu0W_9lII9aiS4rUVp2jXwIvCruo27sG6&index=1&t=3s",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/discordbot",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1twCBXbYjua0GHF-pUjrxOUEwLFg-EYLQ/view?usp=sharing",
    image: discordbot,
  },
  {
    name: "Dall-e-Image Generator",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=dGdA9z6gBkM&list=PLu0W_9lII9aiS4rUVp2jXwIvCruo27sG6&index=2",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/dalleimagegenerator",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1Rb41Fu63J85RDZsPuhcgGt0E89-dfxRx/view?usp=sharing",
    image: dalleimage,
  },
  {
    name: "LangChain Functions Testing",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=cQUUkZnyoD0&list=PLu0W_9lII9aiS4rUVp2jXwIvCruo27sG6&index=3",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/langchaintesting",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1kf8nQ0Y9Cnch8cdhBWaNvG38LKApbE2q/view?usp=sharing",
    image: langchaintesting,
  },
  {
    name: "LangChain Article Generator",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=eEeqw8-hNZk&list=PLu0W_9lII9aiS4rUVp2jXwIvCruo27sG6&index=4",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/langchainarticle",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1sRyNYjDQI_hMYv1MHuvNDR3PcewnwHtl/view?usp=sharing",
    image: langchainarticle,
  },
  {
    name: "Voice GPT",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=pXvfcoag-VE&list=PLu0W_9lII9aiS4rUVp2jXwIvCruo27sG6&index=5",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/aivoiceassisted",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1DFY1_2CNByyzDQpXl_cey1Opg5qXAYWk/view?usp=sharing",
    image: aivoiceassisted,
  },
  {
    name: "Open AI Whisper",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=KRhvlB1mOts&list=PLu0W_9lII9aiS4rUVp2jXwIvCruo27sG6&index=6",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/openaiwhisper",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1f1j3DAjJEWE98o1AkgmL4gNs4PwvKz6M/view?usp=sharing",
    image: openaiwhisper,
  },
  {
    name: "Codeswear",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/playlist?list=PLu0W_9lII9agtWvR_TZdb_r0dNI8-lDwG",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/codeswear",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1znFWjghg8Grkpmfs1r0au7egUFJB3PlB/view?usp=sharing",
    image: codeswear,
  },
  {
    name: "Stock Management System",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=RtgG9kZpyg4",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/stockmanagement",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/1eafl8xY4v0hB7hl-iEGslcp-kyvLg1iO/view?usp=sharing",
    image: inventory,
  },
  {
    name: "Shahnawaz Portfolio",
    follow: "COURSE FOLLOWED FROM: ",
    follow_link: "https://www.youtube.com/watch?v=0fYi8SGA20k&t=7154s",
    git: "GITHUB REPO: ",
    source_code_link: "https://github.com/Shahnawaz1990/my-portfolio",
    video: "Video: ",
    video_link: "https://drive.google.com/file/d/182g0N9VsKEMMd3UXPsVwyLnoPrT4_in_/view?usp=sharing",
    image: portfolio,
  },

];

export { services, technologies, experiences, testimonials, projects };
